-- MySQL Script generated by MySQL Workbench
-- Sun Jun 24 10:38:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `AddressKey` INT(11) NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(128) NOT NULL,
  `City` VARCHAR(64) NOT NULL,
  `State` VARCHAR(2) NOT NULL,
  `Zip` VARCHAR(16) NOT NULL,
  `Country` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`AddressKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customers` ;

CREATE TABLE IF NOT EXISTS `Customers` (
  `CustomerID` VARCHAR(4) NOT NULL,
  `Type` TINYINT UNSIGNED ZEROFILL NOT NULL,
  `PrimaryContact` VARCHAR(4) NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `AddressKey` INT(11) NOT NULL,
  PRIMARY KEY (`CustomerID`),
  UNIQUE INDEX `CustomerID` (`CustomerID` ASC),
  INDEX `fk_Customers_Address1_idx` (`AddressKey` ASC),
  CONSTRAINT `fk_Customers_Address1`
    FOREIGN KEY (`AddressKey`)
    REFERENCES `Address` (`AddressKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Emails` ;

CREATE TABLE IF NOT EXISTS `Emails` (
  `EmailKey` INT(11) NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`EmailKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persons` ;

CREATE TABLE IF NOT EXISTS `Persons` (
  `PersonID` VARCHAR(4) NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `AddressKey` INT(11) NOT NULL,
  `EmailKey` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonID`),
  UNIQUE INDEX `PersonID` (`PersonID` ASC),
  INDEX `fk_Persons_Address1_idx` (`AddressKey` ASC),
  INDEX `fk_Persons_Email1_idx` (`EmailKey` ASC),
  CONSTRAINT `fk_Persons_Address1`
    FOREIGN KEY (`AddressKey`)
    REFERENCES `Address` (`AddressKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persons_Email1`
    FOREIGN KEY (`EmailKey`)
    REFERENCES `Emails` (`EmailKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Invoices` ;

CREATE TABLE IF NOT EXISTS `Invoices` (
  `InvoiceID` VARCHAR(6) NOT NULL,
  `CustomerID` VARCHAR(4) NOT NULL,
  `SalespersonID` VARCHAR(4) NOT NULL,
  `Date` DATE NOT NULL,
  `LinkedTicket` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`InvoiceID`),
  UNIQUE INDEX `InvoiceID` (`InvoiceID` ASC),
  INDEX `fk_Invoices_Customers1_idx` (`CustomerID` ASC),
  INDEX `fk_Invoices_Persons1_idx` (`SalespersonID` ASC),
  CONSTRAINT `fk_Invoices_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Persons1`
    FOREIGN KEY (`SalespersonID`)
    REFERENCES `Persons` (`PersonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Products` ;

CREATE TABLE IF NOT EXISTS `Products` (
  `ProductID` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`ProductID`),
  UNIQUE INDEX `ProductID` (`ProductID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `MovieTicket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MovieTicket` ;

CREATE TABLE IF NOT EXISTS `MovieTicket` (
  `ProductID` VARCHAR(4) NOT NULL,
  `Date` VARCHAR(64) NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `AddressKey` INT(11) NOT NULL,
  `TheatreNum` VARCHAR(3) NOT NULL,
  `Cost` DOUBLE NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_MovieTicket_Products_idx` (`ProductID` ASC),
  INDEX `fk_MovieTicket_Address1_idx` (`AddressKey` ASC),
  CONSTRAINT `fk_MovieTicket_Address1`
    FOREIGN KEY (`AddressKey`)
    REFERENCES `Address` (`AddressKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovieTicket_Products`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ParkingPass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ParkingPass` ;

CREATE TABLE IF NOT EXISTS `ParkingPass` (
  `ProductID` VARCHAR(4) NOT NULL,
  `Cost` DOUBLE NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Refreshments_Products_idx` (`ProductID` ASC),
  CONSTRAINT `fk_ParkingPass_Products`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Purchases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Purchases` ;

CREATE TABLE IF NOT EXISTS `Purchases` (
  `PurchaseKey` INT(11) NOT NULL AUTO_INCREMENT,
  `InvoiceID` VARCHAR(6) NOT NULL,
  `ProductID` VARCHAR(4) NOT NULL,
  `Quantity` INT(11) NOT NULL,
  PRIMARY KEY (`PurchaseKey`),
  UNIQUE INDEX `PurchaseCombo` (`InvoiceID` ASC, `ProductID` ASC),
  INDEX `fk_Purchases_Invoices1_idx` (`InvoiceID` ASC),
  INDEX `fk_Purchases_Products1_idx` (`ProductID` ASC),
  CONSTRAINT `fk_Purchases_Invoices1`
    FOREIGN KEY (`InvoiceID`)
    REFERENCES `Invoices` (`InvoiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchases_Products1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Refreshments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Refreshments` ;

CREATE TABLE IF NOT EXISTS `Refreshments` (
  `ProductID` VARCHAR(4) NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `Cost` DOUBLE NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Refreshments_Products1_idx` (`ProductID` ASC),
  CONSTRAINT `fk_Refreshments_Products1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SeasonPass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SeasonPass` ;

CREATE TABLE IF NOT EXISTS `SeasonPass` (
  `ProductID` VARCHAR(4) NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `Cost` DOUBLE NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_SeasonPass_Products_idx` (`ProductID` ASC),
  CONSTRAINT `fk_SeasonPass_Products`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
